# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task2_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.samplingContainer = QtWidgets.QWidget(self.centralwidget)
        self.samplingContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.samplingContainer.setObjectName("samplingContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.samplingContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_mainChannel = QtWidgets.QLabel(self.samplingContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mainChannel.sizePolicy().hasHeightForWidth())
        self.label_mainChannel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mainChannel.setFont(font)
        self.label_mainChannel.setObjectName("label_mainChannel")
        self.verticalLayout.addWidget(self.label_mainChannel)
        self.mainChannel = PlotWidget(self.samplingContainer)
        self.mainChannel.setMinimumSize(QtCore.QSize(0, 300))
        self.mainChannel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainChannel.setObjectName("mainChannel")
        self.verticalLayout.addWidget(self.mainChannel)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.samplingSlider = QtWidgets.QSlider(self.samplingContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplingSlider.sizePolicy().hasHeightForWidth())
        self.samplingSlider.setSizePolicy(sizePolicy)
        self.samplingSlider.setMouseTracking(False)
        self.samplingSlider.setMaximum(3)
        self.samplingSlider.setTracking(True)
        self.samplingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.samplingSlider.setInvertedAppearance(False)
        self.samplingSlider.setInvertedControls(False)
        self.samplingSlider.setObjectName("samplingSlider")
        self.verticalLayout.addWidget(self.samplingSlider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.secondaryChannel = PlotWidget(self.samplingContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondaryChannel.sizePolicy().hasHeightForWidth())
        self.secondaryChannel.setSizePolicy(sizePolicy)
        self.secondaryChannel.setMaximumSize(QtCore.QSize(16777215, 200))
        self.secondaryChannel.setObjectName("secondaryChannel")
        self.verticalLayout.addWidget(self.secondaryChannel)
        self.horizontalLayout.addWidget(self.samplingContainer)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.composerContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composerContainer.sizePolicy().hasHeightForWidth())
        self.composerContainer.setSizePolicy(sizePolicy)
        self.composerContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.composerContainer.setMaximumSize(QtCore.QSize(8377215, 16777215))
        self.composerContainer.setObjectName("composerContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.composerContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.composer_control = QtWidgets.QWidget(self.composerContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composer_control.sizePolicy().hasHeightForWidth())
        self.composer_control.setSizePolicy(sizePolicy)
        self.composer_control.setMinimumSize(QtCore.QSize(0, 0))
        self.composer_control.setObjectName("composer_control")
        self.formLayout = QtWidgets.QFormLayout(self.composer_control)
        self.formLayout.setObjectName("formLayout")
        self.label_composer = QtWidgets.QLabel(self.composer_control)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_composer.setFont(font)
        self.label_composer.setObjectName("label_composer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_composer)
        self.label_composer_phase = QtWidgets.QLabel(self.composer_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_composer_phase.sizePolicy().hasHeightForWidth())
        self.label_composer_phase.setSizePolicy(sizePolicy)
        self.label_composer_phase.setObjectName("label_composer_phase")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_composer_phase)
        self.label_composer_mag = QtWidgets.QLabel(self.composer_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_composer_mag.sizePolicy().hasHeightForWidth())
        self.label_composer_mag.setSizePolicy(sizePolicy)
        self.label_composer_mag.setObjectName("label_composer_mag")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_composer_mag)
        self.label_composer_freq = QtWidgets.QLabel(self.composer_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_composer_freq.sizePolicy().hasHeightForWidth())
        self.label_composer_freq.setSizePolicy(sizePolicy)
        self.label_composer_freq.setObjectName("label_composer_freq")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_composer_freq)
        self.phase_input = QtWidgets.QLineEdit(self.composer_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phase_input.sizePolicy().hasHeightForWidth())
        self.phase_input.setSizePolicy(sizePolicy)
        self.phase_input.setObjectName("phase_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phase_input)
        self.freq_input = QtWidgets.QLineEdit(self.composer_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_input.sizePolicy().hasHeightForWidth())
        self.freq_input.setSizePolicy(sizePolicy)
        self.freq_input.setObjectName("freq_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.freq_input)
        self.magnitude_input = QtWidgets.QLineEdit(self.composer_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnitude_input.sizePolicy().hasHeightForWidth())
        self.magnitude_input.setSizePolicy(sizePolicy)
        self.magnitude_input.setObjectName("magnitude_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.magnitude_input)
        self.verticalLayout_2.addWidget(self.composer_control)
        self.composer_draw = QtWidgets.QPushButton(self.composerContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composer_draw.sizePolicy().hasHeightForWidth())
        self.composer_draw.setSizePolicy(sizePolicy)
        self.composer_draw.setMaximumSize(QtCore.QSize(100, 16777215))
        self.composer_draw.setObjectName("composer_draw")
        self.verticalLayout_2.addWidget(self.composer_draw)
        self.composer_channel_1 = PlotWidget(self.composerContainer)
        self.composer_channel_1.setObjectName("composer_channel_1")
        self.verticalLayout_2.addWidget(self.composer_channel_1)
        self.composer_channel_2 = PlotWidget(self.composerContainer)
        self.composer_channel_2.setObjectName("composer_channel_2")
        self.verticalLayout_2.addWidget(self.composer_channel_2)
        self.comboBox = QtWidgets.QComboBox(self.composerContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addWidget(self.composerContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSample = QtWidgets.QMenu(self.menubar)
        self.menuSample.setObjectName("menuSample")
        self.menuComposer = QtWidgets.QMenu(self.menubar)
        self.menuComposer.setObjectName("menuComposer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionSave_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionSave_as_PDF.setObjectName("actionSave_as_PDF")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCompose_signal = QtWidgets.QAction(MainWindow)
        self.actionCompose_signal.setObjectName("actionCompose_signal")
        self.actionSampling = QtWidgets.QAction(MainWindow)
        self.actionSampling.setObjectName("actionSampling")
        self.actionRe_construction = QtWidgets.QAction(MainWindow)
        self.actionRe_construction.setObjectName("actionRe_construction")
        self.actionShow_on_secondary_channel = QtWidgets.QAction(MainWindow)
        self.actionShow_on_secondary_channel.setObjectName("actionShow_on_secondary_channel")
        self.actionHide_secondary_channel = QtWidgets.QAction(MainWindow)
        self.actionHide_secondary_channel.setObjectName("actionHide_secondary_channel")
        self.actionSave_composed_as = QtWidgets.QAction(MainWindow)
        self.actionSave_composed_as.setObjectName("actionSave_composed_as")
        self.actionShow_reconstructed_on_main_channel = QtWidgets.QAction(MainWindow)
        self.actionShow_reconstructed_on_main_channel.setObjectName("actionShow_reconstructed_on_main_channel")
        self.menuFile.addAction(self.actionOpen_file)
        self.menuFile.addAction(self.actionSave_as_PDF)
        self.menuFile.addAction(self.actionExit)
        self.menuSample.addAction(self.actionSampling)
        self.menuSample.addAction(self.actionRe_construction)
        self.menuSample.addAction(self.actionShow_on_secondary_channel)
        self.menuSample.addAction(self.actionHide_secondary_channel)
        self.menuSample.addAction(self.actionShow_reconstructed_on_main_channel)
        self.menuComposer.addAction(self.actionSave_composed_as)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuComposer.menuAction())
        self.menubar.addAction(self.menuSample.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_mainChannel.setText(_translate("MainWindow", "Main Channel"))
        self.label_composer.setText(_translate("MainWindow", "Composer"))
        self.label_composer_phase.setText(_translate("MainWindow", "Phase"))
        self.label_composer_mag.setText(_translate("MainWindow", "Magnitude"))
        self.label_composer_freq.setText(_translate("MainWindow", "Frequency"))
        self.composer_draw.setText(_translate("MainWindow", "Draw sin"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose the sin"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSample.setTitle(_translate("MainWindow", "Signal processes"))
        self.menuComposer.setTitle(_translate("MainWindow", "Composer"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionOpen_file.setShortcut(_translate("MainWindow", "Shift+O"))
        self.actionSave_as_PDF.setText(_translate("MainWindow", "Save as PDF"))
        self.actionSave_as_PDF.setShortcut(_translate("MainWindow", "Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionCompose_signal.setText(_translate("MainWindow", "Compose signal"))
        self.actionSampling.setText(_translate("MainWindow", "Sampling"))
        self.actionRe_construction.setText(_translate("MainWindow", "Re-construction"))
        self.actionShow_on_secondary_channel.setText(_translate("MainWindow", "Show on secondary channel"))
        self.actionHide_secondary_channel.setText(_translate("MainWindow", "Hide secondary channel"))
        self.actionSave_composed_as.setText(_translate("MainWindow", "Save composed as"))
        self.actionShow_reconstructed_on_main_channel.setText(_translate("MainWindow", "Show reconstructed on main channel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

